### PR TITLE
Add maintainers

### PR DESCRIPTION
**Pull request by jakirkham**
This PR will adds some people as maintainers on the `salt` feedstock.

As this is your first time being added, you will receive an invitation (via email) to join conda-forge. In particular, this will add you to the `salt` team. Once accepted, you will be given commit privileges on the `salt` feedstock/repo (here 😉) and be signed up for notifications on this feedstock. Feel free to configure these as you see fit. Any future feedstocks that you sign up for or added to (with your permission of course) will automatically add you to the relevant team for those feedstocks and give you commit privileges on them.

Regarding making changes, the norm here is to fork the repo, add a branch with your changes to your fork, and PR it back to the main repo. Once merged, these will trigger deployments via CI to the conda-forge channel.

Please let me know if you have any questions and welcome to conda-forge.

cc @basepi @nmadhok

### CODE REVIEW

**Comment by jakirkham** [comment]
Going to let this sit for a bit to see if there are any more people interested in being added.

**Comment by nmadhok** [comment]
@jakirkham Great! Feel free to add me to the conda-forge/libcloud project as well! I'll go over the projects over the weekend and read contribution guidelines for them! Thanks!

**Comment by jakirkham** [comment]
Sure, adding you in this PR ( https://github.com/conda-forge/apache-libcloud-feedstock/pull/2 ), @nmadhok.

**Comment by danielfrg** [comment]
This is amazing :)

**Comment by jakirkham** [comment]
This is why it is a good idea to tell people we added there cool packages. 😉

Please feel free to merge this whenever, @danielfrg.

**Pull request merged**
